apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: org-ekstern-proxy
  namespace: org
  labels:
    team: org
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://org-ekstern-proxy.ekstern.dev.nav.no"
    - "https://org-ekstern-proxy.intern.dev.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      rules:
        - application: nom-api
          namespace: nom
  env:
    - name: WHITELIST_FILE
      value: '/whitelist/dev.json'
    - name: OTEL_JAVAAGENT_LOGGING  # Bli kvitt Otel loggingen https://opentelemetry.io/docs/zero-code/java/agent/configuration/#java-agent-logging-output
      value: none